routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

$this->get('/', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login')->name('login_auth');

$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
$this->post('register', 'Auth\RegisterController@register')->name('register_auth');

Route::prefix('portal')
->middleware('auth')
->group(function(){
	$this->post('logout', 'Auth\LoginController@logout')->name('logout');

	Route::get('users/reset-password', 'UsersController@reset_password_form')->name('reset_password_form');
	Route::post('users/reset-password', 'UsersController@reset_password')->name('reset_password');

	Route::get('/', 'HomeController@index')->name('home');
	Route::resource('calculator', 'CalculatorController')->only(['index',]);

	Route::get('usage/data', 'UsageController@data')->name('usage.data');
	Route::resource('usage', 'UsageController');

	Route::resource('appliances', 'UserAppliancesController');

	Route::prefix('settings')
	->middleware('AdminAccess')
	->group(function(){
		Route::resource('set-appliances', 'AppliancesController')->only(['index', 'create', 'store', 'edit', 'update']);
		Route::resource('rate', 'RateController')->only(['index', 'create', 'store', 'edit', 'update']);
		Route::resource('advisories', 'AdvisoriesController')->only(['index', 'create', 'store', 'edit', 'update']);

		Route::get('users/generate-password', 'UsersController@generate_password')->name('generate_password');
		Route::resource('users', 'UsersController');
	});
});

app/Appliance.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Appliance extends Model
{
    public $table = 'appliances';
    public $timestamps = true;

    protected $dates = [
        'created_at', 'updated_at'
    ];

    protected $fillable = [
    	'name', 'wattage', 'created_at', 'updated_at' 
	];

	public function user()
	{
    	return $this->hasOne('App\UserAppliance', 'appliance_id', 'id');
	}
}

app/Http/Controllers/AppliancesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Appliance;

class AppliancesController extends Controller
{
	public function index(Request $request)
	{
		$search = '';
		$query = new Appliance;

		if($request->has('search'))
		{
			$search = trim($request->search);
			$query = $query->where('name', 'LIKE', "$search%");
		}

		$rows = $query->orderBy('name', 'ASC')->paginate(10);

		$data = compact('search', 'rows');
		return view('appliances.index', $data);
	}

	public function create()
	{
		$route = route('set-appliances.store');
		$method = '';
		$name = old('name');
		$wattage = old('wattage');

		$data = compact('route', 'method', 'name', 'wattage');
		return view('appliances.create-form', $data);
	}

	public function store(Requests\AppliancesStoreRequest $request)
	{
		$input = $request->only('name', 'wattage');
		Appliance::create($input);
        return redirect()->route('set-appliances.create')->with('success', 'Appliance successfully added!');
	}

	public function edit($id)
	{
		$route = route('set-appliances.update', $id);
		$method = method_field('PUT');
		$row = Appliance::first();
		$name = $row->name;
		$wattage = $row->wattage;

		$data = compact('route', 'method', 'name', 'wattage');
		return view('appliances.create-form', $data);
	}

	public function update($id, Requests\AppliancesUpdateRequest $request)
	{
		$input = $request->only('name', 'wattage');
		Appliance::whereId($id)->update($input);
        return redirect()->route('set-appliances.edit', $id)->with('success', 'Appliance successfully updated!');
	}
}

resources/views/appliances/create-form.blade.php
@extends('layouts.master')

@section('content')
    <br>
    <div class="card">
        <header class="card-header">
            &nbsp;&nbsp;&nbsp;&nbsp;
            <nav class="breadcrumb" aria-label="breadcrumbs">
                <ul>
                    <li><a href="{{ route('set-appliances.index') }}">Appliances</a></li>
                    <li class="is-active"><a href="#" aria-current="page">Form</a></li>
                </ul>
            </nav>
            </header>
            <div class="card-content">
                @include('layouts.validation-messages')
                <div class="content">
        
                    <form action="{{ $route }}" method="post">

                        <div class="columns field is-horizontal">
                            <div class="column is-2">
                                <div class="field-label is-normal">
                                    <label class="label is-normal" for="agency_code">Name</label>
                                </div>
                            </div>
                            <div class="column is-10">
                                <div class="field-body is-fullwidth">
                                    <div class="field">
                                        <p class="control">
                                            <input class="input is-normal" type="text" name="name" id="name" value="{{ $name }}">
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="columns field is-horizontal">
                            <div class="column is-2">
                                <div class="field-label is-normal">
                                    <label class="label is-normal" for="wattage">Wattage</label>
                                </div>
                            </div>
                            <div class="column is-2">
                                <div class="field-body is-fullwidth">
                                    <div class="field">
                                        <p class="control">
                                            <input class="input is-normal" type="text" name="wattage" id="wattage" value="{{ $wattage }}">
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <div class="column is-8">&nbsp;</div>
                        </div>

                        <div class="columns field is-horizontal">
                            <div class="column is-2">
                                <div class="field-label is-normal"></div>
                            </div>
                            <div class="column is-2">
                                <div class="field-body is-fullwidth">
                                    <div class="field">
                                        <p class="control">
                                            {!! csrf_field() !!}
                                            {!! $method !!}
                                            <button class="button is-info is-normal">Submit</button>
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <div class="column is-8">&nbsp;</div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
@endsection

@push('scripts')
<script type="text/javascript">
</script>
@endpush

resources/views/appliances/index.blade.php
@extends('layouts.master')

@section('content')
    <br>
    <div class="columns">
        <div class="column is-9">
            <h3 class="title is-3"><i class="fa fa-dropbox"></i>&nbsp;Appliances</h3>
        </div>
        <div class="column is-3">
            <form action="" method="get">
                <div class="field has-addons">
                    <div class="control">
                        <a class="button is-static"><i class="fa fa-search"></i></a>
                    </div>
                    <div class="control">
                        <input class="input is-normal" type="text" name="search" id="search" value="{{ $search }}">
                    </div>
                    <div class="control">
                        <button class="button is-dark">Search</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <table class="table is-bordered is-narrow is-hoverable is-fullwidth">
        <thead>
            <tr>
                <th width="5%" class="has-text-centered"><a href="{{ route('set-appliances.create') }}"><i class="fa fa-plus-circle fa-lg"></i></a></th>
                <th width="10%" class="has-text-centered">Wattage</th>
                <th width="850%">Name</th>
            </tr>
        </thead>
        <tbody>
            @foreach($rows as $row)
            <tr>
                <td class="has-text-centered">
                    @if(Auth::user()->access == 0)
                    <a href="{{ route('set-appliances.edit', $row->id) }}" title="Edit Appliance Details">
                        <i class="fa fa-edit"></i>
                    </a>
                    @else
                    <i class="fa fa-edit"></i>
                    @endif
                </td>
                <td class="has-text-centered">{{ $row->wattage }}</td>
                <td>{{ $row->name }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    {!! $rows->appends(['search'=>$search])->links('vendor.pagination.default') !!}
        
@endsection

resources/views/appliances/show.blade.php
@extends('layouts.master')

@section('content')
    <br>
    <div class="card">
        <header class="card-header">
            &nbsp;&nbsp;&nbsp;&nbsp;
            <nav class="breadcrumb" aria-label="breadcrumbs">
                <ul>
                    <li><a href="#">Drivers</a></li>
                    <li class="is-active"><a href="#" aria-current="page">Details</a></li>
                </ul>
            </nav>
        </header>
        <div class="card-content">
            <div class="content">

                <div class="field is-horizontal">
                    <div class="field-label">
                        <label class="label" >License Number</label>
                    </div>
                    <div class="field-body">
                        <div class="field is-expanded">
                            <p class="control">
                                {{ $license_number }}
                            </p>
                        </div>
                    </div>
                </div>

                <div class="field is-horizontal">
                    <div class="field-label">
                        <label class="label" >License Type</label>
                    </div>
                    <div class="field-body">
                        <div class="field">
                            <div class="control is-expanded">
                                {{ $license_type }}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="field is-horizontal">
                    <div class="field-label">
                        <label class="label" >License Number</label>
                    </div>
                    <div class="field-body">
                        <div class="field is-expanded">
                            <p class="control">
                                {{ date('F d, Y', strtotime($expiry_date)) }}
                            </p>
                        </div>
                    </div>
                </div>

                <div class="field is-horizontal">
                    <div class="field-label">
                        <label class="label" for="agency_code">Agency Code</label>
                    </div>
                    <div class="field-body">
                        <div class="field is-narrow">
                            <p class="control">
                                {{ $agency_code }}
                            </p>
                        </div>
                    </div>
                </div>

                <div class="field is-horizontal">
                    <div class="field-label">
                        <label class="label" for="name">Name</label>
                    </div>
                    <div class="field-body">
                        <div class="field">
                            <p class="control is-expanded">
                                {{ $first_name }} {{ $middle_name }} {{ $last_name }}
                            </p>
                        </div>
                    </div>
                </div>

                <div class="field is-horizontal">
                    <div class="field-label">
                        <label class="label" for="birth_date">Birth Date</label>
                    </div>
                    <div class="field-body">
                        <div class="field is-expanded">
                            <p class="control">
                                {{ date('F d, Y', strtotime($birth_date)) }}
                            </p>
                        </div>
                    </div>
                </div>

                <div class="field is-horizontal">
                    <div class="field-label">
                        <label class="label" for="birth_date">Gender</label>
                    </div>
                    <div class="field-body">
                        <div class="field is-expanded">
                            <div class="control">
                                {{ strtoupper($gender) }}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="field is-horizontal">
                    <div class="field-label">
                        <label class="label">Nationality</label>
                    </div>
                    <div class="field-body">
                        <div class="field is-expanded">
                            <p class="control">
                                {{ $nationality }}
                            </p>
                        </div>
                    </div>
                </div>

                <div class="field is-horizontal">
                    <div class="field-label">
                        <label class="label">Height</label>
                    </div>
                    <div class="field-body">
                        <div class="field is-expanded">
                            <p class="control">
                                {{ $height }} cm
                            </p>
                        </div>
                    </div>
                </div>

                <div class="field is-horizontal">
                    <div class="field-label">
                        <label class="label">Weight</label>
                    </div>
                    <div class="field-body">
                        <div class="field is-expanded">
                            <p class="control">
                                {{ $weight }} kg
                            </p>
                        </div>
                    </div>
                </div>

                <div class="field is-horizontal">
                    <div class="field-label">
                        <label class="label">E-Mail</label>
                    </div>
                    <div class="field-body">
                        <div class="field">
                            <p class="control">
                                {{ $email }}
                            </p>
                        </div>
                    </div>
                </div>

                <div class="field is-horizontal">
                    <div class="field-label">
                        <label class="label" for="address">Address</label>
                    </div>
                    <div class="field-body">
                        <div class="field">
                            <p class="control is-expanded">
                                {{ $address }}
                            </p>
                        </div>
                    </div>
                </div>

                <div class="field is-horizontal">
                    <div class="field-label">
                        <label class="label" for="city">City</label>
                    </div>
                    <div class="field-body">
                        <div class="field">
                            <p class="control is-expanded">
                                {{ $city }}
                            </p>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection